# Generated by Django 5.2.12 on 2026-03-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='fashion', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='drama_name',
            field=models.CharField(default='K-drama', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default', upload_to='products/'),
            preserve_default=False,
        ),
    ]
