# Generated by Django 5.2.12 on 2026-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0002_product_category_product_drama_name_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='fashion', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='drama_name',
            field=models.CharField(default='K-drama', max_length=100),
        ),
    ]
